#!/bin/bash
#   Copyright 2016 RIFT.IO Inc
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# 
# script to start a build. This is run inside a container
#
# 24 June 2016 -- Jeremy Mordkoff -- Genesis

HERE=$(realpath $(dirname $0))
OSM_JENKINS=$(dirname $HERE)
. $OSM_JENKINS/common/all_funcs
export OSM_MDG=riftware
OSM_load_config


if [ -d riftware ]; then
	INFO "reusing existing workspace"
	cd riftware
	git pull 
else
	INFO "cloning MDG riftware from $OSM_GIT_URL/riftware"
	git clone $OSM_GIT_URL/riftware
	cd riftware
	INFO "install pre-requisites"
	bash ./scripts/vm_image/mkcontainer --modes build
fi

INFO "no build script yet"
RC=1

INFO "done RC = $RC"
exit $RC



