version: '2'
services:

  son-emu:
    image: registry.sonata-nfv.eu:5000/son-emu
    container_name: son-emu
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "host"
    pid: "host"
    privileged: true
    ports:
     #REST api
     - "5001:5001"
    entrypoint: 
     - "/son-emu/utils/ci/entrypoint_docker-compose.sh"
    command: [python, src/emuvim/examples/son-monitor_default_topo.py]


