- hosts: localhost
  tasks:
   - name: updates apt
     apt: update_cache=yes
     
   - name: install python-dev
     apt: pkg=python-dev state=installed

   - name: install python-zmq
     apt: pkg=python-zmq state=installed

   - name: install libzmq-dev
     apt: pkg=libzmq-dev state=installed

   - name: install libffi-dev
     apt: pkg=libffi-dev state=installed

   - name: install libssl-dev
     apt: pkg=libssl-dev state=installed

   - name: install pip
     apt: pkg=python-pip state=installed

   - name: install setuptools
     pip: name=setuptools state=latest

   - name: install zerorpc
     pip: name=zerorpc state=latest

   - name: install tabulate
     pip: name=tabulate state=latest

   - name: install argparse
     pip: name=argparse state=latest

   - name: install networkx
     pip: name=networkx state=latest

   - name: install six
     pip: name=six state=latest

   - name: install ryu
     pip: name=ryu state=latest
     
   - name: install oslo.config
     pip: name=oslo.config state=latest

   - name: install pytest
     pip: name=pytest state=latest

   - name: install Flask
     pip: name=Flask state=latest

   - name: install flask_restful
     pip: name=flask_restful state=latest

   - name: install requests
     pip: name=requests state=latest

   - name: install docker
     pip: name=docker version=2.0.2

   - name: install prometheus_client
     pip: name=prometheus_client state=latest

   - name: install latest urllib3 (fix error urllib3.connection.match_hostname = match_hostname)
     pip: name=urllib3 state=latest

   - name: install iptc
     pip: name=python-iptables state=latest



