#!/bin/bash
#
#   Copyright 2017 Sandvine
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# 
# Authors:
#    - Michael Marchetti - mmarchetti@sandvine.com
# 

HERE=$(realpath $(dirname $0))
OSM_JENKINS=$(dirname $HERE)
. $OSM_JENKINS/common/all_funcs

# SET YOU MDG repository name here
export OSM_MDG=osmclient
OSM_load_config

NOTEST=""
if [ "$1" = "--notest" ]; then
    shift
    NOTEST="y"
fi

OSM_git_checkout "$@"

apt update
apt install -y docker.io

# cleanup all pre-existing builds.
# deb pkg build fails if previous build image is present
rm -rf deb_dist dist

docker build -t $OSM_MDG .
DOCKER_ARGS="-v $(pwd):$(pwd) -w $(pwd) -u $(id -u):$(id -g) $OSM_MDG"

if [ -n "$NOTEST" ]; then
    docker run $DOCKER_ARGS /bin/bash -c "./docker_command.sh $(id -u -n) $(id -g -n) tox"
fi

docker run $DOCKER_ARGS /bin/bash -c "./docker_command.sh $(id -u -n) $(id -g -n) tox -e build"

RC=$?
INFO "done, RC=$RC"
exit $RC
